---
fixtures:
  repositories:
    apache:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-apache
    auditd:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_core
    augeasproviders_grub:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_grub
    augeasproviders_ssh:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_ssh
    augeasproviders_sysctl:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_sysctl
    augeasproviders_puppet:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_puppet
    compliance_mapper:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-compliance_markup
    datacat:
      branch: 5.X
      repo: https://github.com/simp/puppet-datacat
    elasticsearch:
      branch: 5.X
      repo: https://github.com/simp/puppet-elasticsearch
    haveged:
      branch: 5.X
      repo: https://github.com/simp/puppet-haveged
    simpcat:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-concat
    logrotate:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-logrotate
    file_concat:
      branch: 5.X
      repo: https://github.com/simp/puppet-lib-file_concat
    iptables:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-iptables
    java:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-java
    logstash:
      branch: 5.X
      repo: https://github.com/simp/puppet-logstash
    oddjob:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-oddjob
    pam:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-pam
    pki:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-pki
    rsync:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-rsync
    rsyslog:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-rsyslog
    simplib:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-simplib
    simp_elasticsearch:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-simp_elasticsearch
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
    stunnel:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-stunnel
    sysctl:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-sysctl
    tcpwrappers:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    simp_logstash: "#{source_dir}"
